apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kv-ros-test-5
  title: Frontend Z
  annotations:
    github.com/project-slug: spire-test/kv-ros-test-5
  links:
    - url: https://console.cloud.google.com/apis/dashboard?project=spire-ros-5lmr
      title: Google OAuth Consent Screen
spec:
  type: service
  lifecycle: experimental
  owner: github/kv-platform
  system: kv-ros
---
apiVersion: "backstage.io/v1alpha1"
kind: "System"
metadata:
  name: "initRosSystemMed"
  title: "System med GCP-Project-Id"
  labels:
    gcp-project-id: "prosjekt-prod-1234"
spec:
  owner: "insane-team"
---
apiVersion: "backstage.io/v1alpha1"
kind: "System"
metadata:
  name: "initRosSystemUten"
  title: "System uten GCP-Project-Id"
spec:
  owner: "insane-team"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "Component uten system"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "insane-team"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "Component med system med prosjekt ID"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "insane-team"
  system: "initRosSystemMed"
---
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "Component med system uten prosjekt ID"
  tags:
  - "internal"
spec:
  type: "service"
  lifecycle: "production"
  owner: "insane-team"
  system: "initRosSystemUten"
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: insane-team
  description: The Insane GCP-team
spec:
  type: team
  profile:
    displayName: The Insane GCP-team
  members: [hans.sande_bekk.no]
